
type_to_name = {
    'track': 'трек',
    'artist': 'исполнитель',
    'album': 'альбом',
    'playlist': 'плейлист',
    'video': 'видео',
    'user': 'пользователь',
    'podcast': 'подкаст',
    'podcast_episode': 'эпизод подкаста',
    'genre': 'жанр',
}

genres_k_v = {
    'all': 'Музыка всех жанров',
    'pop': 'Поп',
    'ruspop': 'Русская поп-музыка',
    'disco': 'Диско',
    'kpop': 'K-pop',
    'turkishpop': 'Турецкая поп-музыка',
    'uzbekpop': 'Узбекская поп-музыка',
    'japanesepop': 'J-pop',
    'israelipop': 'Израильская поп-музыка',
    'azerbaijanpop': 'Азербайджанская поп-музыка',
    'hyperpopgenre': 'Гиперпоп',
    'allrock': 'Рок',
    'rusrock': 'Русский рок',
    'rnr': 'Рок-н-ролл',
    'prog': 'Прогрессивный рок',
    'postrock': 'Построк',
    'newwave': 'New Wave',
    'ukrrock': 'Украинский рок',
    'folkrock': 'Фолк-рок',
    'stonerrock': 'Стоунер-рок',
    'hardrock': 'Хард-рок',
    'turkishrock': 'Турецкий рок',
    'rock': 'Иностранный рок',
    'israelirock': 'Израильский рок',
    'indie': 'Инди',
    'local-indie': 'Местное инди',
    'metal': 'Метал',
    'progmetal': 'Прогрессив',
    'epicmetal': 'Эпический',
    'folkmetal': 'Фолк',
    'gothicmetal': 'Готический',
    'industrial': 'Индастриал',
    'sludgemetal': 'Сладж',
    'postmetal': 'Постметал',
    'extrememetal': 'Экстрим',
    'numetal': 'Ню-метал',
    'metalcoregenre': 'Металкор',
    'classicmetal': 'Хэви-метал',
    'thrashmetal': 'Трэш-метал',
    'deathmetal': 'Дэт-метал',
    'blackmetal': 'Блэк-метал',
    'doommetal': 'Дум-метал',
    'alternativemetal': 'Альтернативный метал',
    'alternative': 'Альтернатива',
    'posthardcore': 'Постхардкор',
    'hardcore': 'Хардкор',
    'turkishalternative': 'Турецкая альтернативная музыка',
    'electronics': 'Электроника',
    'techno': 'Техно',
    'house': 'Хаус',
    'trance': 'Транс',
    'breakbeatgenre': 'Брейкбит',
    'bassgenre': 'Бейс',
    'dnb': 'Драм-н-бэйс',
    'dubstep': 'Дабстеп',
    'triphopgenre': 'Трип-хоп',
    'ukgaragegenre': 'UK Garage',
    'idmgenre': 'IDM',
    'ambientgenre': 'Эмбиент',
    'newage': 'Нью-эйдж',
    'lounge': 'Лаундж',
    'experimental': 'Экспериментальная',
    'dance': 'Танцевальная',
    'phonkgenre': 'Фонк',
    'edmgenre': 'EDM',
    'rap': 'Рэп и хип-хоп',
    'rusrap': 'Русский рэп',
    'foreignrap': 'Иностранный рэп',
    'turkishrap': 'Турецкий рэп и хип-хоп',
    'israelirap': 'Израильский рэп и хип-хоп',
    'rnb': 'R&B',
    'soul': 'Соул',
    'funk': 'Фанк',
    'jazz': 'Джаз',
    'tradjazz': 'Традиционный',
    'conjazz': 'Современный',
    'bebopgenre': 'Бибоп',
    'vocaljazz': 'Вокальный джаз',
    'smoothjazz': 'Смус-джаз',
    'bigbands': 'Биг бэнды',
    'blues': 'Блюз',
    'reggae': 'Регги',
    'reggaeton': 'Реггетон',
    'dub': 'Даб',
    'ska': 'Ска',
    'punk': 'Панк',
    'postpunk': 'Постпанк',
    'folk': 'Музыка мира',
    'rusfolk': 'Русская',
    'tatar': 'Татарская',
    'celtic': 'Кельтская',
    'balkan': 'Балканская',
    'eurofolk': 'Европейская',
    'jewish': 'Еврейская',
    'eastern': 'Восточная',
    'african': 'Африканская',
    'latinfolk': 'Латиноамериканская',
    'amerfolk': 'Американская',
    'romances': 'Романсы',
    'argentinetango': 'Аргентинское танго',
    'armenian': 'Армянская',
    'georgian': 'Грузинская',
    'azerbaijani': 'Азербайджанская',
    'caucasian': 'Кавказская',
    'turkishclassical': 'Турецкая классическая музыка',
    'arabesquemusic': 'Арабеска',
    'turkishfolk': 'Турецкая народная музыка',
    'estrada': 'Эстрада',
    'rusestrada': 'Русская',
    'shanson': 'Шансон',
    'country': 'Кантри',
    'soundtrack': 'Саундтреки',
    'films': 'Из фильмов',
    'tvseries': 'Из сериалов',
    'animated': 'Из мультфильмов',
    'videogame': 'Из видеоигр',
    'animemusic': 'Аниме',
    'musical': 'Мюзиклы',
    'bollywood': 'Болливуд',
    'relax': 'Лёгкая музыка',
    'meditation': 'Медитация',
    'children': 'Детская музыка со всего мира',
    'naturesounds': 'Звуки природы и шум города',
    'bard': 'Авторская песня',
    'rusbards': 'Русская',
    'foreignbard': 'Иностранная',
    'forchildren': 'Детская',
    'lullaby': 'Колыбельные',
    'fairytales': 'Аудиосказки',
    'poemsforchildren': 'Стихи для детей',
    'podcasts': 'Подкасты',
    'classicalmusic': 'Классика',
    'vocal': 'Вокал',
    'modern': 'Современная классика',
    'classical': 'Мировая классика',
    'classicalmasterpieces': 'Шедевры мировой классики',
    'fiction': 'Художественная литература',
    'romancenovel': 'Про любовь',
    'historicalfiction': 'Про историю',
    'sciencefiction': 'Фантастика',
    'fantasyliterature': 'Фэнтези',
    'actionandadventure': 'Приключения и экшн',
    'crimeandmystery': 'Детективы и триллеры',
    'horrorandthrillers': 'Ужасы и мистика',
    'dramaliterature': 'Драматургия',
    'childrensliterature': 'Книги для детей и подростков',
    'nonfictionliterature': 'Нон-фикшн',
    'community': 'Общество и философия',
    'work': 'О бизнесе',
    'technologies': 'О технологиях',
    'hls': 'О здоровом образе жизни',
    'selfdevelopment': 'О саморазвитии',
    'psychologyandphilosophy': 'Психология и воспитание',
    'religionandspirituality': 'О духовном',
    'biographyandmemoirs': 'Биографии и мемуары',
    'popularsciencebooks': 'Популярно о науке',
    'booksnotinrussian': 'Аудиокниги на иностранном языке',
    'audiobooksinenglish': 'На английском',
    'audiobooks': 'Разговорное',
    'other': 'Другое',
    'sport': 'Спортивная',
    'holiday': 'Праздничная',
}

template_search_uncorrect = [
    'karaoke',
    'disco',
    'hit',
    'hits',
]
